name: setup-universe

on:
  pull_request:

jobs:
  setup-universe:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y -v --no-nvidia universe
