name: update-docker-manifest

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update-docker-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update Docker manifest for 'autoware-universe'
        uses: ./.github/actions/update-docker-manifest
        with:
          package-name: autoware-universe
